### PR TITLE
Updated namespace

### LINKED ISSUE #15: Namespace?
Change from APIPHP to Api? or ApiPhp? I even thought about an imaginary name: API Factory or SDK Factory. 😄

### PR DESCRIPTION
**Pull request by Nyholm**
This will fix #15

### CODE REVIEW

**Comment by sagikazarmark** [comment]
Afaik FOS uses FOS as it's an abbreviation: https://github.com/FriendsOfSymfony/FOSHttpCache/blob/master/src/CacheInvalidator.php#L12

**Comment by sagikazarmark** [comment]
But I am ok with `Fapi` as well

**Comment by Nyholm** [comment]
FAPI\Boilerplate?

**Comment by Nyholm** [comment]
Merge if you like it. Im happy to change.

**Comment by sagikazarmark** [comment]
FAPI suggests that it's an abbreviation. WDYT?

**Comment by Nyholm** [comment]
I'll update

**Comment by sagikazarmark** [comment]
Do you agree or something? 😄

**Comment by Nyholm** [comment]
hehe. I really do not have any opinion in this matter. Im happy with `FAPI` =)

**Comment by sagikazarmark** [comment]
Okay, well, so until we find a better name, let's go with this. Do you rename the orga as well? FriendsOfAPI?

**Comment by Nyholm** [comment]
I think we should. But lets do that within a couple of days.. See if the name feels right =)

**Comment by Nyholm** [comment]
Thank you for merging.

**Pull request merged**
